---
title: "3_study1descriptives"
author: "Jen Richmond"
date: "13/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)

```


```{r}
clean_data <- read_csv(here("data", "dateStudy1data_clean.csv"))
```

Categorical variable: group
Continuous variable: perception_1, mean_att, mean_int

Mean ratings for gain and loss manipulation check by group

```{r}

summary_manipcheck <- clean_data %>%
  group_by(group) %>%
  summarise(gf_M = mean(manipulation_check_gf_1, na.rm = TRUE),
            gfSD = sd(manipulation_check_gf_1, na.rm = TRUE), 
            gfN = n(), 
            gfStdErr = gfSD/sqrt(gfN),
            lf_M = mean(manipulation_check_lf_1, na.rm = TRUE),
            lfSD = sd(manipulation_check_lf_1, na.rm = TRUE), 
            lfN = n(), 
            lfStdErr =  lfSD/sqrt(lfN))

  print(summary_manipcheck)

```

Mean ratings for perception by group

```{r}

summary_perception <- clean_data %>%
  group_by(group) %>%
  summarise(mean = mean(perception_1, na.rm=TRUE), 
            sd = sd(perception_1, na.rm=TRUE), 
            n = n(), 
            stderr = sd / sqrt(n))

  print(summary_perception)

```

Mean ratings for attitude by group

```{r}

summary_attitude <- clean_data %>%
  group_by(group) %>%
  summarise(mean = mean(mean_att, na.rm=TRUE), 
            sd = sd(mean_att, na.rm=TRUE), 
            n = n(), 
            stderr = sd / sqrt(n))

  print(summary_attitude)

```

Mean ratings for intention by group

```{r}

summary_intention <- clean_data %>%
  group_by(group) %>%
  summarise(mean = mean(mean_int, na.rm=TRUE), 
            sd = sd(mean_int, na.rm=TRUE), 
            n = n(), 
            stderr = sd / sqrt(n))

  print(summary_intention)

```

All mean ratings

```{r}

summary_data <- clean_data %>%    
  group_by(group) %>%
  summarise(gf_M = mean(manipulation_check_gf_1, na.rm = TRUE),
            gfSD = sd(manipulation_check_gf_1, na.rm = TRUE), 
            gfN = n(), 
            gfStdErr = gfSD/sqrt(gfN),
            lf_M = mean(manipulation_check_lf_1, na.rm = TRUE),
            lfSD = sd(manipulation_check_lf_1, na.rm = TRUE), 
            lfN = n(), 
            lfStdErr =  lfSD/sqrt(lfN),
            per_M = mean(perception_1, na.rm = TRUE),
            perSD = sd(perception_1, na.rm = TRUE), 
            perN = n(), 
            perStdErr =  perSD/sqrt(perN),
            att_M = mean(mean_att, na.rm = TRUE),
            attSD = sd(mean_att, na.rm = TRUE), 
            attN = n(), 
            attStdErr =  attSD/sqrt(attN),
            int_M = mean(mean_att, na.rm = TRUE),
            intSD = sd(mean_att, na.rm = TRUE), 
            intN = n(), 
            intStdErr =  intSD/sqrt(intN))

print(summary_data)

```

Saving summary data (M, SD, N, StdErr) as a csv

```{r}

summary_data %>%
  write_csv(here("data", "summary_data.csv" ))

```
