---
title: "Study 2 Plots"
author: "Jenny Chen"
date: "11/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading packages
 
```{r message=FALSE, warning=FALSE}

library(tidyverse)
library(here)
library(ggeasy)

```

# Reading in data

```{r message=FALSE, warning=FALSE}

clean_data <- read_csv(here("data", "dateStudy2data_clean.csv"))

summary_data <- read_csv(here("data", "summary_data.csv"))

manipcheck <- read_csv(here("data", "manipcheck.csv"))

per_att_int <- read_csv(here("data", "per_att_int.csv"))

```

# Calculating mean ratings for gain and loss manipulation check by group using facet_wrap()

```{r}

glimpse(manipcheck)

  manipcheck$group[manipcheck$group == "gain"] <- "Gain"
  manipcheck$group[manipcheck$group == "loss"] <- "Loss"
  manipcheck$question[manipcheck$question == "positive_benefits"] <- "To what extent did the information emphasise /n the benefits of using open science practices?"
  manipcheck$question[manipcheck$question == "negative_conseq"] <- "To what extent did the information emphasise the consequences of not using open science practices?"

manipcheck %>%
    ggplot(aes(x = group, y = mean, fill = group)) +
    geom_col(width = 0.7, position = "dodge", show.legend = FALSE) +
    scale_y_continuous(expand = c(0,0),
                       limits = c(0,5)) +
    theme_classic() +
    facet_wrap(~ question) +
    geom_errorbar(aes(ymin=mean-StdErr, ymax=mean+StdErr),
                  size=.3,
                  width=.2,
                  position=position_dodge(.9)) +
     labs(x="Condition", y="Mean ratings")

```

# Calculating mean ratings for perception, attitude, and intention by group using facet_wrap()

Categorical variable: group
Continuous variable: perception_1, mean_att, mean_int

```{r}

glimpse(per_att_int)

  per_att_int$group[per_att_int$group == "gain"] <- "Gain"
  per_att_int$group[per_att_int$group == "loss"] <- "Loss"
  per_att_int$question[per_att_int$question == "perception"] <- "Perception"
  per_att_int$question[per_att_int$question == "attitude"] <- "Attitude"
  per_att_int$question[per_att_int$question == "intention"] <- "Intention"

per_att_int_ordered <- per_att_int
per_att_int_ordered$question <- factor(per_att_int_ordered$question,
                         levels = c("Perception", "Attitude", "Intention"))

per_att_int_ordered %>%
    ggplot(aes(x = group, y = mean, fill = group)) +
    geom_col(width = 0.7, position = "dodge", show.legend = FALSE) +
    scale_y_continuous(expand = c(0,0),
                       limits = c(0,5)) +
    theme_classic() +
    facet_wrap(~ question) +
    geom_errorbar(aes(ymin=mean-StdErr, ymax=mean+StdErr),
                  size=.3,
                  width=.2,
                  position=position_dodge(.9)) +
     labs(x="Condition", y="Mean ratings")

```
